### ISSUE TITLE
Unable to make a connection to BIG-IQ

### ISSUE THREAD

**Issue by r-anthonypineda** [leonardobdes/BIGREST#22]
Hello - I tried to make a connection to our new BIG-IQ. I get the error below. admin user account has the following roles: Administrator Role, F5 Device Trust User and  Device Manager.

```
>>> bq = BIGIQ("10.14.49.94","admin","xZxZxZxZx",session_verify=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/appviewx/apineda/venv/lib/python3.8/site-packages/bigrest/big.py", line 96, in __init__
    self._connect()
  File "/home/appviewx/apineda/venv/lib/python3.8/site-packages/bigrest/big.py", line 499, in _connect
    raise RESTAPIError(response, self.debug)
bigrest.common.exceptions.RESTAPIError: 
Status:
401
Response Body:
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>webd</center>
</body>
</html>
```

**Comment by u1163139** [comment]
My BIG-IQ is running 8.2.0

**Comment by leonardobdes** [comment]
Sorry for the long delay in the response, but this is probably why:
[https://my.f5.com/manage/s/article/K43725273](https://my.f5.com/manage/s/article/K43725273)

**Comment by leonardobdes** [comment]
Closing.
If you still have problems, add a comment and I will reopen the issue.
